services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "mysql123"
      MYSQL_DATABASE: "mysql"
      MYSQL_USER: "misho"
      MYSQL_PASSWORD: "mysql123"
    volumes:
      - db_sql_data:/var/lib/mysql
    networks:
      - mysql
    restart: always

  wordpress:
    image: wordpress:latest
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: "mysql:3306"
      WORDPRESS_DB_USER: "misho"
      WORDPRESS_DB_PASSWORD: "mysql123"
      WORDPRESS_DB_NAME: "mysql"
    networks:
      - mysql
    restart: always

volumes:
  db_sql_data:

networks:
  mysql:
    driver: bridge
